### ISSUE TITLE
AWS Region for Fake SQS

### ISSUE THREAD

**Issue by jpbernius** [mozart-analytics/sqsd#12]
Hello,

I am using your `sqsd` in combination with [adamw/elasticmq](https://github.com/adamw/elasticmq).
In order for this SQS Fake to work with `sqsd`, I need to set a fake region. In this case, I use `elasticmq` as the region.

As of this, I keep getting the following exception:
```
Caught: java.lang.IllegalArgumentException: Cannot create enum from elasticmq value!
java.lang.IllegalArgumentException: Cannot create enum from elasticmq value!
	at com.amazonaws.regions.Regions.fromName(Regions.java:73)
	at sqsd.run(sqsd.groovy:49)
```

If I take a real Region, it will not work with my queue URL, which is `http://aws_sqs:9324/queue/worker`.

Any Idea on how I can setup `sqsd`  for this scenario?

**Comment by petter-ka** [comment]
Hi,

I am facing with this problem too... Any solution/setup for this?

Thanks

**Comment by Danielss89** [comment]
Did anyone find a solution to this?
